from .agent import (
    Agent,
    AgentState,
    LANGGRAPH_AVAILABLE,
    LocalRAGInput,
    LocalRAGRetrieveTool,
    PROMPT,
    build_agent,
)
from .config import (
    AppConfig,
    DEFAULT_CHECKPOINT_DB,
    DEFAULT_INDEX_DB_FILENAME,
    DEFAULT_INDEX_VERSION,
    DEFAULT_MAX_CONTEXT_TOKENS,
    DEFAULT_KEYWORD_WEIGHT,
    DEFAULT_MANIFEST_FILENAME,
    DEFAULT_SESSION_ID,
    DEFAULT_TOP_K,
    EmbeddingConfig,
    GenerationConfig,
    HarnessConfig,
    IndexBuildConfig,
    JobConfig,
    MetadataRerankConfig,
    ModelConfig,
    PermissionConfig,
    RetrievalConfig,
    RetrievalRuntimeConfig,
    RuntimeConfig,
    ScholarConfig,
    build_app_config,
    parse_bool_env,
)
from .exceptions import EmbeddingError, ProviderError, SearchBackendError
from .jobs import BackgroundJobManager, JobNotFound, JobRecord
from .permissions import PermissionDenied, ToolPermissionPolicy
from .research_plan import (
    ResearchPlan,
    ResearchPlanInput,
    ResearchPlanTool,
    format_research_plan,
    latest_research_plan,
)
from .scholar_search import (
    ScholarSearchResponse,
    ScholarSearchService,
    SerpApiGoogleScholarBackend,
    build_scholar_query_planner,
    build_scholar_search_service,
    merge_scholar_hits,
    parse_scholar_organic_results,
    plan_scholar_queries,
    run_scholar_search,
)
from .scholar_export import (
    build_scholar_filename,
    render_scholar_search_markdown,
    save_scholar_search_markdown,
)
from .scholar_tools import ScholarSearchInput, ScholarSearchTool
from .skills import LoadSkillInput, LoadSkillTool, Skill, SkillRegistry
from .structured_trace import StructuredTraceWriter
from .token_estimation import HeuristicTokenEstimator, select_token_estimator
from .indexing import (
    BuildReport,
    IndexedRetriever,
    build_index,
    default_index_dir_for_kb,
    ensure_index_for_kb,
    inspect_index,
    is_index_directory,
    load_index,
    resolve_existing_index_for_kb,
)
from .corpus import (
    chunk_text,
    load_corpus_text,
    load_docx_text,
    load_markdown_directory_text,
    load_markdown_text,
    tokenize,
)
from .evaluation import evaluate_retrieval_cases, hit_rate_at_k, ndcg_at_k, reciprocal_rank
from .retrieval import (
    DashScopeEmbeddingClient,
    EmbeddingBackend,
    LocalRAGStore,
    Retriever,
    SearchResult,
    build_bm25_idf,
    build_idf,
    dense_cosine_similarity,
    normalize_dense_vector,
    normalize_scores,
    stable_hash,
)
from .web_fetch import fetch_url
from .web_search import DuckDuckGoHtmlSearchBackend
from .web_tools import WebFetchInput, WebFetchTool, WebSearchInput, WebSearchTool
from .web_types import FetchResult
from .web_types import ScholarHit, ScholarResource
from .web_ui import serve_ui
from .runtime import (
    append_log,
    build_sqlite_checkpointer,
    ensure_log_file,
    extract_final_answer,
    extract_messages_from_result,
    get_graph_state,
    get_thread_config,
    run_demo,
    run_graph_invoke,
    run_graph_stream,
    run_or_resume,
    shorten_text,
)


def main(argv=None):
    from .cli import main as _main

    return _main(argv)


def parse_args(argv=None):
    from .cli import parse_args as _parse

    return _parse(argv)


__all__ = [
    "Agent",
    "AgentState",
    "AppConfig",
    "BackgroundJobManager",
    "BuildReport",
    "DashScopeEmbeddingClient",
    "DEFAULT_CHECKPOINT_DB",
    "DEFAULT_INDEX_DB_FILENAME",
    "DEFAULT_INDEX_VERSION",
    "DEFAULT_MAX_CONTEXT_TOKENS",
    "DEFAULT_KEYWORD_WEIGHT",
    "DEFAULT_MANIFEST_FILENAME",
    "DEFAULT_SESSION_ID",
    "DEFAULT_TOP_K",
    "EmbeddingBackend",
    "EmbeddingConfig",
    "EmbeddingError",
    "FetchResult",
    "evaluate_retrieval_cases",
    "GenerationConfig",
    "HarnessConfig",
    "HeuristicTokenEstimator",
    "hit_rate_at_k",
    "IndexBuildConfig",
    "IndexedRetriever",
    "JobConfig",
    "JobNotFound",
    "JobRecord",
    "LANGGRAPH_AVAILABLE",
    "LocalRAGInput",
    "LocalRAGRetrieveTool",
    "LocalRAGStore",
    "LoadSkillInput",
    "LoadSkillTool",
    "ModelConfig",
    "MetadataRerankConfig",
    "PermissionConfig",
    "PermissionDenied",
    "PROMPT",
    "ProviderError",
    "Retriever",
    "RetrievalConfig",
    "RetrievalRuntimeConfig",
    "ResearchPlan",
    "ResearchPlanInput",
    "ResearchPlanTool",
    "RuntimeConfig",
    "ScholarConfig",
    "ScholarHit",
    "ScholarResource",
    "ScholarSearchInput",
    "ScholarSearchResponse",
    "ScholarSearchService",
    "ScholarSearchTool",
    "build_scholar_filename",
    "render_scholar_search_markdown",
    "save_scholar_search_markdown",
    "SearchResult",
    "SearchBackendError",
    "SerpApiGoogleScholarBackend",
    "Skill",
    "SkillRegistry",
    "StructuredTraceWriter",
    "ToolPermissionPolicy",
    "serve_ui",
    "stable_hash",
    "DuckDuckGoHtmlSearchBackend",
    "WebFetchInput",
    "WebFetchTool",
    "WebSearchInput",
    "WebSearchTool",
    "append_log",
    "build_agent",
    "build_app_config",
    "build_bm25_idf",
    "build_idf",
    "build_index",
    "build_sqlite_checkpointer",
    "chunk_text",
    "default_index_dir_for_kb",
    "dense_cosine_similarity",
    "ensure_index_for_kb",
    "ensure_log_file",
    "extract_final_answer",
    "extract_messages_from_result",
    "fetch_url",
    "format_research_plan",
    "get_graph_state",
    "get_thread_config",
    "inspect_index",
    "is_index_directory",
    "load_corpus_text",
    "load_docx_text",
    "load_index",
    "load_markdown_directory_text",
    "load_markdown_text",
    "latest_research_plan",
    "main",
    "merge_scholar_hits",
    "ndcg_at_k",
    "normalize_dense_vector",
    "normalize_scores",
    "parse_args",
    "parse_bool_env",
    "parse_scholar_organic_results",
    "plan_scholar_queries",
    "reciprocal_rank",
    "resolve_existing_index_for_kb",
    "run_demo",
    "run_graph_invoke",
    "run_graph_stream",
    "run_or_resume",
    "run_scholar_search",
    "select_token_estimator",
    "shorten_text",
    "tokenize",
    "build_scholar_query_planner",
    "build_scholar_search_service",
]
